### ISSUE TITLE
In my application #include <openssl/pem.h> throws "file not found"

### ISSUE THREAD

**Issue by erenerturk1** [jedisct1/openssl-wasm#4]
I used your prebuilt `libcrypto.a` and I get these errors:
```
./openssl.cpp:5:10: fatal error: 'openssl/pem.h' file not found
    5 | #include <openssl/pem.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.
./common/common.cpp:6:10: fatal error: 'openssl/sha.h' file not found
    6 | #include <openssl/sha.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.
```
I tried to fix this by downloading the `include` files in the repo, but they are of no help as they generate more and more errors the more I create patches and download new ones to fix them. How could I solve this?

**Comment by jedisct1** [comment]
`.h` files and libraries are distinct things. libraries contain the actual code. `.h` files are just interface definitions for programs written in C.

You need to tell your C compiler where the include files with the OpenSSL headers are. For example by adding the `-I /path/to/openssl/includes` option.
